---
output:
  pdf_document: default
  html_document: default
---

\section{Introduction}
Data visualisation is a method of conveying data in an easily digestible manner through graphics. It is an important aspect of data presentation and allows key information to be quickly identified by the observer. Very many subject areas rely on such visualisations to relay messages that may get lost or have less impact when presented as written word or raw numbers. 

The main objective of visualisation is to create figures that display the data accurately in an aesthetic manner, giving non-misleading messages in a format that is pleasing to the eye. A good visualisation strikes a balance between aesthetics and information, where the aesthetic features are designed such that they 'enhance the message of the visualisation' [@wilke2019]. 

An incorrect balance of aesthetics to information can lead to figures that are misleading, confusing, or unengaging. Wilke discusses the way in which, for example, a research scientist with limited design experience may produce a visualisation displaying the data in an informative manner, but fail to draw immediate attention to the desired message, and on the other hand, someone with a main interest in the aesthetic design of a visualisation could create a figure that is very pleasing to the eye, but create a misleading visualisation in the process.

This literature review will discuss a range of publications discussing various aspects of data visualisation with a focus on how poor or uninformed visualisation design can produce misleading figures, as well as how such visualisations may be abused to deliberately deceive the observer. Starting with publications discussing general good visualisation practice, the discussion will then lead on to look at studies investigating the implementation of different visualisation practices, from which inspiration will be drawn to design the study for this paper.

\section{Good Visualisation Practice}
The book \textit{'Fundamentals of Data Visualization'} [@wilke2019] is renowned as \textit{'an excellent reference about producing and understanding static figures, figures'} [see @wilkerev] and described as being \textit{'suitable to be used as a reference manual'} [see @hwang2020]. Thus, this book provides a good basis to understanding the principles behind data visualisation, and how to create effective, informative and aesthetic figures. 

In the book, Wilke discusses a variety of topics under the data visualisation umbrella, from relatively simple but important and often overlooked ideas such as deciding on coordinate systems, axis scales and colouring, to how to visualise distributions, trends and geospatial data. This literature review will focus on the areas being investigated in the 'Empirical Study of Data Visualisation' survey; namely coordinate systems, axis scaling, colouring for bar charts, alongside stacked and grouped bar charts, as well as axis scaling and formats for time series plots.

\subsection{Axis Scaling}
In discussing coordinate systems and axis scaling, Wilke highlights that, prior to deciding on a coordinate system, it is important to consider the form the data will take, and where the data will be positioned, as well as how many dimensions this data takes. The example used is a classic two-dimensional scatter plot, in which each data value is represented by a point positioned in a distinct location on the 2d plane, and thus two scales are required to define where this location falls, traditionally with a linear scale and horizontal x-axis with the y-axis perpendicular to this. 

Alternative coordinate systems can include the perpendicular model with non-linear axes, or circular or ‘curved’ models such as polar coordinates in addition to flipped axes, where the dependent variable is represented by the x-axis as opposed to the y. 

'An Empirical Study of Data Visualisation' will be mainly analysing perception of categorical bar charts, for which the 'locations' are the category as defined by the x-axis and the bar height. It will be discussed how the perception of these locations could be altered to stray from 'good practice', and how these alterations may mislead the observer. 

In discussion of the linear, two-dimensional cartesian system, the author describes the various formulations that this system can take, in terms of variables with the same or different units. For example, if two variables with different units are represented perpendicular to one another on a cartesian system, the designer has the freedom to stretch or compress the data in a way to best represent the data and, as Wilke states, 'maintain a valid visualisation of the data'. 

Another point of interest mentioned by Wilke here is that the ratio of x to y- axis should be such that 'important differences in position are noticeable'. This is regarded as good practice by Wilke, but could potentially be exploited as discussed by @Few2016; the aspect ratio can be manipulated to make differences appear larger depending on the story that the creator wishes to sell. On the other hand, Wilke does state that it is 'important differences' that should be noticeable, and so may relate to differences that are already significant and crucial to see, and which may be minimised by an inappropriate aspect ratio. 

For example, consider a company facing a drop in profits from one time step to another. An aspect ratio minimising the height in comparison to the width can allow this difference to appear smaller. On the other side of this coin, a company may have marginal profit gain between two time steps, and can abuse principles of perception to lengthen the y-axis as compared to the x, potentially making the difference seem larger.

This will be considered when writing the survey, as the perceived differences in position will be tested when changing features such as y-axis scaling or aspect ratio. A standard practice as laid out by Wilke is that, for two variables with the same unit, the aspect ratio should ensure that the space between ticks for each variable are equal in size.

After this, Wilke goes on to discuss logarithmic scaling, which will be investigated in this study alongside axis truncation. Conversely to what will be investigated in this study, he talks about both logarithmic scaling and log-transformed data whereas this study will consider logarithmic scaling alone. He describes how this is a preferable format when dealing with ratios, and explains that this is a result of the fact that the product of linear numbers is analogous to the sum of the logarithms when using a logarithmic scale. Additionally, data containing a large variation in magnitudes is also stated to benefit from logarithmic scaling.

The book also explains the differences between plotting the original data on a logarithmic scale, and log-transformed data on a linear scale. In terms of mathematics, these are analogous, but Wilke states that plotting the original data on a log-transformed scale is favoured as this shows the true data values as opposed and allows easier reader interpretation of values. This will be considered and the original data on a logarithmic scale will be investigated. A study with narrower scope on only logarithmic scaling and log-transformed data, or even just a study of axis scaling, may allow to test both log-transformations and log-scalings, however the wide scope of this study means that study topics have to be reduced.

\subsection{Colour}
A very important aspect of visualisation is the use of colour. Colour is a very useful means of showing features of the data such as groupings and gradients of values, as well as to highlight key values. It could be said that colour works as a third dimension to the visualisation, showing another dimension of information on top of that shown by the position or size of the data points. It is important that the use of colour is carefully thought out, and not just applied with aesthetics in mind. Aesthetics are, or course, an important factor in colouring a visualisation, as 'pretty' colouring allows the visualisations to be eye-catching and memorable, which can be beneficial to, for example, brands or pharmaceutical companies giving regular data presentations as very aesthetic plots are more likely to be remembered. 

Once again, Wilke has a good explanation and examples of each type of colour usage. There can be defined to be two types of colour scale, or palette; qualitative or quantitative. Qualitative colour scales do not have a logical order of colouring and are used for data for which the ordering of either values of groupings is inconsequential, such as for much categorical data. The latter, quantitative colour scales, provide gradients of colour and can consist of either a gradual scale moving through two or more colours, or a single colour with varying saturation. This type of scale provides a continuous colouring and can show grouping tendencies in continuous data, and is also often used in maps. As mentioned by Wilke, continuous graduated colour scales have the ability to show the degree to which two values are similar. There are several examples of both types of colour scale, and those discussed in this study will involve the defaults for both R and Python, and two colourblind friendly palettes; viridis and greyscale. 

It is important to consider that the visualisations may be viewed by people with colourblindness in order to ensure they are accessible to any viewer. Using certain colour scales may be problematic for someone who is colourblind as they may find it difficult to distinguish between certain colours, and thus lose the impact and story told by the third dimension of the visualisation. @colourb has a good explanation of how visualisation can be modified to accommodate those with the condition. Using colours such as red and green, or a traffic light scaling is not ideal, as these can be harder to distinguish. However, red and green is a very common and useful combination to use, as it can give a highly intuitive story of 'good' and 'bad' values, or positive and negative. Shaffer describes that this can be worked around by adding arrows, icons or annotations to distinguish values. Another workaround is to, for example, use very light green and very dark red as a saturation as opposed to hue comparison. The viridis palette has been specifically formulated to allow easier perception for people with colourblindness.

Colour can very easily be misused, however, and a common misuse, described by Wilke, is to colour each individual bar in a simple bar chart. This colouring reveals no additional information about the data and labeling is much preferred as the added colour here draws attention away from the message of the data. However, colour is useful for stacked or grouped bar charts to distinguish between groupings. 

\subsection{Bar Charts}
When discussing good practice for bar charts, Wilke discusses many aspects of visualisation including axis alignment and bar ordering, as well as discussion on stacked and grouped bars. The axis alignment, ie vertical vs horizontal bars, is dependent on the data being visualised. Wilke uses the example of bars with labels that may become either difficult to read or unaesthetic when shown on the vertical chart, but appear clearer on the horizontal. 

In terms of bar ordering, Wilke discusses that it is important aesthetically to order bars from largest to smallest, given there is no pre-specified ordering in the data, such as age ranges. Bar plots will be discussed in more detail in the past study reviews.

##### PIE CHARTS
@wilke2910 section 10.1
@pie
##### PIE CHARTS 


##### TIME SERIES
section 13.1
##### TIME SERIES


##### BRIEFLY: 3D AND WHY IT'S BAD
section 26.1
##### BRIEFLY: 3D AND WHY IT'S BAD

##### TAXONOMY PAPER 
@taxonomy
##### TAXONOMY PAPER

\section{Studies in Visualisation}
There is a large amount of research and literature surrounding the topic of misleading visualisations, looking into how various techniques can either deliberately or unintentionally deceive an observer in the message of the data. Results from some of these papers will be replicated, as well as used to form hypotheses which this survey will investigate. A large amount of the literature exploring misleading tactics in data visualisation focuses mainly on bar plots and line plots for categorical and time series data, and so this is what the study and literature review will focus on. 

The 2020 paper "The Deceptive Potential of Common Design Tactics Used in Data Visualizations" [@claire-obrian], as the title suggests, explores how using different design tactics may mislead the person seeing the visualisation. Similarly to "An Empirical Study of Data Visualisation", the Claire and O'Brian paper uses a survey to explore how deceptive visualisation techniques can be employed as well as their impact on perception of the data. The survey discussed in this paper presents the participant with four plots; a bar plot, a line plot, a pie chart and a bubble plot. Additionally to changing aesthetic features of the plots themselves, the study investigates the use of exaggerated, leading titles, for example one control plot has the title " Home Sales Show Increase From 2015 - 2016", which is altered to "Huge Increase in Home Sales From 2015 – 2016!". The control plots consist of using a y-axis scaling beginning at 0 for the bar and line plots, a standard pie chart, and a bubble plot with proportionally sized bubbles, all alongside the non-exaggerated titles. The altered plots involve truncating the y-scale for the bar and line plots, making the pie chart in 3D, and arbitrarily altering the sizes of the bubbles on the bubble plot. The altered plots are referred to as the "deceptive" plots. The survey used sets of plots as crossed between deceptive aesthetics and deceptive titles; two had control aesthetics, one with the control title and one for the exaggerated title, and two had deceptive aesthetics with one having the exaggerated titling.

With regard to truncated axes, Claire and O'Brian asked participants to subjectively judge the difference between two data points using a 6 point scale ranging from "a little" to "a lot". For both the bar plot and line plot it was found the the use of a truncated scale increases the perceived difference between the data points. The use of a truncated scale is also discussed by @YANG2021, whereby 5 empirical studies were performed in order to assess the effect of altering the scale in this way. The first of the 5 studies once again assessed how large the difference between data points is perceived to be in the truncated plot as compared to a control, again using a subjective scale from "Not at all different" to "Extremely different" on a 7 point scale. This scale differed, however, in the way that a midpoint label of "Moderately different" was provided. The 7 point scale may be preferable to the 6 point scale as the 7 point has a defined midpoint at 4, whereas the 6 point does not. This study once again concludes that the differences in data points tended to be perceived as larger than for the control plot. Alongside these studies, a 2014 blog post [@parikh_2014] discusses axis truncation and its effect on perceived data point difference for bar plots alongside other aesthetic features. The first example shows how truncating the y-axis of a bar plot can over-exaggerate differences in the heights of the bars, perhaps leading to incorrect observations regarding comparisons of values within the data. 

The paper @stackscale performs a similar study, but instead investigates the use of 'stack-scale', or 'stacked' bar charts and logarithmic scaling. The aim of the study was to explore whether stack-scale bar charts are an effective way to visualise large value data, which is less relevant to since the Ninja Warrior and Sales data are relatively low-valued data compared to the paper, but nevertheless provides a framework for exploring the use of logarithmic scaling and stacked bars in a respondent study. Participants were shown three plots; a control with a linear scale, a bar plot using a stack-scale, and one with logarithmic scaling. The questions asked determined how the different scaling affected accuracy in reading individual values, interpreting differences in values and determining which time-step exhibits the largest difference in values. @logax additionally discusses the use of a logarithmic axis in bar plots, explaining how it is impossible for a zero value to be displayed on this axis, and thus the bar start points are arbitrary and produce an inaccurate representation of the bar height with relation to the true value. To quote the paper, \textit{"Don’t create bar graphs using a logarithmic axis if your goal is to honestly show the data"}. It can be observed that the logarithmic scale makes the perceived difference appear smaller than in the control. 

As well as scaling, another aspect of visualisation design that could potentially mislead the observer is bar width and aspect ratios. When adding a visualisation into a publication, re-sizing the visualisation to fit a specific gap may include altering the aspect ratio, in turn affecting the length to width ratio of the bars in a bar plot. As explored by Steven Few in a 2016 article for the \textit{'Visual Business Intelligence Newsletter'} [@Few2016], altering this ratio can affect viewer perception in the way of a narrower and taller image distorting bars to appear longer, and vice versa, meaning that perceived differences between bar heights may be affected. 

Part 2 of the survey will be based around investigating this idea, alongside how the reading of exact values is affected. The second section of the survey tests whether altering aspect ratio of plots affects interpretation. The purpose of this is to mirror what my occur when visualisations are published, and may be resized to fit the section of the page they sit on. As in [@Few2016], it will be hypothesised that an aspect ratio that effectively narrows the bars may cause overestimation in values, and vice versa, using a ratio that widens bars could lead to underestimation. In the paper, the author discusses how increasing the widths of bars could distract from the bar height as well as take up excessive space on a page. It is also mentioned that wider bars may be "aesthetically displeasing". This section of the survey will test both how bar width alters perceived difference between bars as well as opinions on the aesthetics. The method in the paper also involves altering spaces between bars, including bar plots with spaces at 50% of the bar widths and then reducing the width of the space by a third. Conversely to this, width of spaces between bars will not be considered, only the effective widths of the bars themselves. The author concludes that a length-to-width ratio of 10:1 appears to suffer from perceptual imbalance, but increasing this such that the bars become narrower and longer does not appear to have as much of an impact; the ratio can be increased relatively far with out causing much perceptual imbalance.


An article from the University of Stuttgart [@HuynhHaiDang2017] gives an overview of many types of bar chart, including stacked and grouped bars. The author remarks that grouped bar charts may make the comparison of bars in the same category more difficult, while the stacked bar chart sacrifices ease of comparison of values in the bars for increased spacial efficiency. A 2018 work from the journal of \textit{'Visual Informatics'} [@INDRATMO2018155] also provides a discussion on the use of various forms of stacked and grouped bar charts and their efficacy. The paper notes how a classical stacked bar chart can be useful for overall comparisons as the height of the bar represents the value of the item, with the different attributes depicted as a segmentation of this single bar into different colours. When discussing grouped bar charts it is mentioned that stacked bar charts may be less useful when performing attribute comparisons, in other words comparisons between different categories on the same bar, as a result of the bar segments being non-aligned. This results in comparison taking the form of length judgment as opposed to position judgment. Cleveland and McGill in their 1984 article in the \textit{'Journal of the American Statistical Association'} [@clevelandmcgill] discuss how judgments based on length are likely to be less accurate than those based on position. A grouped bar chart is a way to allow for easy comparison between individual categories, but is discussed to be less effective in overall comparison. 





